function [fitresult, gof] = Lowess_Fit(speeds, quantity, factor)
%CREATEFIT(SPEEDS,QUANTITY,PI)
%  Create a fit.
%
%  Data for 'Lowess fit' fit:
%      X Input : speeds
%      Y Input : quantity
%      Z Output: Pi
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Sep-2017 10:37:10


%% Fit: 'Lowess fit'.
[xData, yData, zData] = prepareSurfaceData( speeds, quantity, factor );

% Set up fittype and options.
ft = fittype( 'lowess' );
opts = fitoptions('Method','LowessFit');
opts.Normalize = 'on';
opts.Span = 0.1;

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

%Plot fit with data.
figure( 'Name', 'Lowess fit' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Lowess fit', 'Factor vs. speeds, load', 'Location', 'NorthEast' );
% Label axes
xlabel speeds
ylabel load
zlabel Pi
grid on
view( -17.5, 24.4 );


